-- Thanh Duy
GO
CREATE TABLE USERS
(
	ID INT NOT NULL PRIMARY KEY
	,USERNAME NVARCHAR(50)
	,PASS NVARCHAR(50)
	,EMAIL NVARCHAR(50)
	,PHONE NVARCHAR(50)
)

GO
CREATE TABLE SHOPCART
(
	ID INT NOT NULL PRIMARY KEY
	,USER_ID INT NOT NULL
	,PRODUCT_ID INT NOT NULL 
)

GO
CREATE TABLE INVOICE
(
	ID INT NOT NULL PRIMARY KEY
	,NGAYBAN DATE
	,USER_ID INT NOT NULL
	,PRODUCT_ID INT NOT NULL 
	,EMPLOYEE_ID INT NOT NULL
)

GO
CREATE TABLE FEEDBACK
(
	ID INT NOT NULL PRIMARY KEY
	,TITLE NVARCHAR(50)
	,DESCRIBE  NVARCHAR(50)
	,USER_ID INT NOT NULL
)

-- SHOPCART FOREIGN KEY
ALTER TABLE SHOPCART ADD FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
ALTER TABLE SHOPCART ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)

-- INVOICE FOREIGN KEY
ALTER TABLE INVOICE ADD FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
ALTER TABLE INVOICE ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
ALTER TABLE INVOICE ADD FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID)

--FEEDBACK FOREIGN KEY
ALTER TABLE FEEDBACK ADD FOREIGN KEY (USER_ID) REFERENCES USERS(ID)